stages:
  download:
    cmd: Rscript stages/download.R
    deps:
    - stages/download.R
    - "https://aact.ctti-clinicaltrials.org/pipe_files"
    outs:
    - download/
  build:
    cmd: Rscript stages/build.R
    deps:
    - stages/build.R
    - download/
    outs:
    - brick/
