stages:
  download:
    cmd: Rscript R/download.R
    deps:
    - R/download.R
    - https://aact.ctti-clinicaltrials.org/pipe_files
    outs:
    - download/
  build:
    cmd: Rscript R/build.R
    deps:
    - R/build.R
    - download/
    outs:
    - data/
