stages:
  download:
    cmd: Rscript stages/download.R
    deps:
    - stages/download.R
    - "https://aact.ctti-clinicaltrials.org/pipe_files"
    outs:
    - download/
  download-metadata:
    cmd: stages/download-metadata.sh
    deps:
    - stages/download-metadata.sh
    outs:
    - metadata/
  build:
    cmd: Rscript stages/build.R
    deps:
    - stages/build.R
    - download/
    - metadata/
    outs:
    - brick/
