stages:
  download:
    cmd: python3 stages/00_download.py
    deps:
    - stages/00_download.py
    - "https://aact.ctti-clinicaltrials.org/pipe_files"
    outs:
    - download/
  unzip:
    cmd: python3 stages/02_unzip.py
    deps:
    - download/
    - stages/02_unzip.py
    outs:
    - unzip/
  build:
    cmd: python3 stages/03_build.py
    deps:
    - stages/03_build.py
    - unzip/
    outs:
    - brick/
